### ISSUE TITLE
Error in nhanes_data_files function

### ISSUE THREAD

**Issue by royarkaprava** [SilentSpringInstitute/RNHANES#17]
Hi,
running 'files <- nhanes_data_files()' produced the error

**Downloading NHANES data file list to C:\Users\ark007\AppData\Local\Temp\RtmpSO4zcU\file315451c614d2
trying URL 'https://wwwn.cdc.gov/Nchs/Nhanes/Search/DataPage.aspx?Component=demographics'
Content type 'text/html; charset=utf-8' length 392824 bytes (383 KB)
downloaded 383 KB

Error in dat[[2]] : subscript out of bounds**

I am not sure how to fix it.

Best,
Arkaprava

**Comment by Kristin-SSI** [comment]
Hi Arkaprava,

Could it it be possible that you are running the version of RNHANES that is on cran? The cran version is not up to date. Can you please uninstall RNHANES, then re-install from github and try again:

library(devtools)
#install_github("silentspringinstitute/RNHANES")

(Asking because files <- nhanes_data_files() is not pulling an error on my machine. )

Best,
Kristin
